name: d3d11_d3d12_vulkan_

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        api: [d3d11, d3d12, vulkan]
    runs-on: "windows-2022"
    env:
      msbuild_path: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v3

      - name: Generate project files
        shell: python
        env:
          API: ${{ matrix.api }}
        run: |
          import subprocess
          import os
          api = os.environ["API"]
          subprocess.run(f"python generate_vs2022_{api}.py")

      - name: Build
        shell: cmd
        run: '"%msbuild_path%\MSBuild.exe" /p:Platform=Windows /p:Configuration=Release /m spartan.sln'
        
      - name: Create artifact
        if: matrix.api != 'd3d12'
        shell: cmd
        run: 'build_scripts\package_artifact.bat ${{ matrix.api }}'
      
      - name: Upload artifact
        if: matrix.api != 'd3d12'
        uses: actions/upload-artifact@v2
        with:
          name: build_${{ matrix.api }}
          path: build_${{ matrix.api }}.7z

  release:
    runs-on: "ubuntu-latest"
    needs:
      - build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Download D3D11 build
        uses: actions/download-artifact@v4.1.7
        with:
          name: build_d3d11
          path: build_d3d11.7z
      
      - name: Download Vulkan build
        uses: actions/download-artifact@v4.1.7
        with:
          name: build_vulkan
          path: build_vulkan.7z
      
      - name: Publish release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            build_d3d11.7z
            build_vulkan.7z
            LICENSE.txt
